### ISSUE TITLE
List of related work

### ISSUE THREAD

**Issue by peterwittek** [networks-lab/metaknowledge#1]
Hi,

Thanks for the amazing work, the library works great. I used and cited it in a [manuscript](http://arxiv.org/abs/1605.08185) and in its accompanying [notebook](http://nbviewer.jupyter.org/github/peterwittek/ipython-notebooks/blob/master/Citation_Network_SDP.ipynb). I wonder if you could create a slot in the documentation where users could shamelessly plug their work.

Thanks.

**Comment by reidmcy** [comment]
Hi,

I am glad the package worked for. We are working on a large release which will change some of the website. At this point the changes are still being figured out and adding a section about other people using _metaknowledge_ will be discussed.

Thank you for your suggestion,
Reid
